name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: node:16-alpine
    steps:
      - name: Install git and rsync 📚
        run: |
          apt-get update && apt-get install -y rsync git

      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build Antora project
        run: |
          cp -R node_modules/@antora/lunr-extension/supplemental_ui/* supplemental-ui/
          npx antora local-antora-playbook.yml --fetch
      - uses: actions/upload-artifact@v3
        with:
          name: docs
          path: docs/
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.2
        if: contains(github.ref,'refs/heads/main') 
        with:
          branch: gh-pages 
          folder: docs 
          clean: true 